### ISSUE TITLE
Error when variable is used as path (instead of string)

### ISSUE THREAD

**Issue by kersulis** [dahong67/CacheVariables.jl#1]
```julia
using CacheVariable
path = "./test.bson"
@cache path x = 5
```

**Comment by kersulis** [comment]
I think the `isfile` check should be part of the expression the macro returns. Whether it's a string or a symbol, the eval would then be done in the enclosing scope.

[Possibly related](https://stackoverflow.com/questions/46447692/julia-scope-of-macro-variables-and-eval)

**Comment by kersulis** [comment]
But feel free to use a type annotation

**Comment by dahong67** [comment]
Fixed by #2
